POST https://git.tech4comp.dbis.rwth-aachen.de/mobsos-success-modeling/apiv2/groups
Content-Type: application/json
Authorization: bGFraG91bmU6UEhscGg2VGkjRWRSPT0rdVk4OWU=

{
"groupID":"5d12b82f25db394803988f701fd8c5c3833558f2b77519dc93e9bab800cacc8541bf378b7f457fff2f6d3d899e6f9cec9bb12ac223054c4d1c5bd5503777e343",
"name":"EvalGroupTuesday",
"isMember":true
}