POST https://git.tech4comp.dbis.rwth-aachen.de/mobsos-success-modeling/apiv2/groups
Content-Type: application/json
Authorization: Basic YWxpY2U6cHdhbGljZQ==

{
"groupID":"ccf714aa5c489b459e61c267e0a1f4501c8f4879fd1a3118454d3aac5d98aca1c049b4929fc45339daf27eab01c2c1b33c642e7e16b6e831505b876e65540ac9",
"name":"Evaluation-Fina",
"isMember":true
}