DROP TABLE LAS2PEERMON.GROUP_INFORMATION;

CREATE TABLE LAS2PEERMON.GROUP_INFORMATION
(
    GROUP_AGENT_ID_MD5 CHARACTER(32) NOT NULL,
    GROUP_AGENT_ID CHARACTER(128) NOT NULL,
    GROUP_NAME VARCHAR(255) NOT NULL,
    PUBLIC BOOLEAN,
    CONSTRAINT GROUP_AGENT_ID_FK FOREIGN KEY (GROUP_AGENT_ID_MD5) REFERENCES LAS2PEERMON.AGENT(AGENT_ID)
);
