DROP TABLE IF EXISTS GROUP_INFORMATION;

CREATE TABLE GROUP_INFORMATION
(
    GROUP_AGENT_ID_MD5 CHAR(32) NOT NULL,
    GROUP_AGENT_ID CHAR(128) NOT NULL,
    GROUP_NAME VARCHAR(255) NOT NULL,
    PUBLIC BOOLEAN,
    CONSTRAINT GROUP_AGENT_ID_FK FOREIGN KEY (GROUP_AGENT_ID_MD5) REFERENCES AGENT(AGENT_ID)
);
