name: Docker Build and Push

on:
  push:
    branches: [master, develop, build-test]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: LAS2PEERMON
      DB_USER: root
      DB_PASSWORD: root
    steps:
    - name: Set up MySQL
      run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE  ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - run: mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} ${{ env.DB_DATABASE }} < ./migrations/las2peermon.sql
    - name: Grant Gradle permissions
      run: chmod +x gradlew
    - name: Test with Gradle
      run: ./gradlew clean test --info 
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Build the Docker image
        run: |
          docker build -t registry.tech4comp.dbis.rwth-aachen.de/rwthacis/mobsos-success-modeling:${{ steps.extract_branch.outputs.branch }} .
      - name: Push to registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PW: ${{ secrets.DOCKER_PW }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PW registry.tech4comp.dbis.rwth-aachen.de
          docker push registry.tech4comp.dbis.rwth-aachen.de/rwthacis/mobsos-success-modeling:${{ steps.extract_branch.outputs.branch }}
